#! /bin/bash
# Background Colors
RED='\033[48;2;255;0;0m'
ORA='\033[48;2;255;142;0m'
YEL='\033[48;2;255;255;0m'
GRE='\033[48;2;0;142;0m'
BLU='\033[48;2;0;192;192m'
PUR='\033[48;2;64;0;152m'

# No Color
NC='\033[0m'

# Print the flag
printf "\n"
printf "${RED}                          ${NC}\n"
printf "${ORA}                          ${NC}\n"
printf "${YEL}                          ${NC}\n"
printf "${GRE}                          ${NC}\n"
printf "${BLU}                          ${NC}\n"
printf "${PUR}                          ${NC}\n"
printf "\n"
