#! /bin/bash
# Background Colors
PINK='\033[48;2;255;118;164m'
WHIT='\033[48;2;255;255;255m'
PURP='\033[48;2;192;17;215m'
BLAC='\033[48;2;44;44;44m'
BLUE='\033[48;2;47;60;190m'

# No Color
NC='\033[0m'

# Print the flag
printf "\n"
printf "${PINK}                          ${NC}\n"
printf "${WHIT}                          ${NC}\n"
printf "${PURP}                          ${NC}\n"
printf "${BLAC}                          ${NC}\n"
printf "${BLUE}                          ${NC}\n"
printf "\n"
