#! /bin/bash
# Background Colors
PINK='\033[48;2;214;2;112m'
PURP='\033[48;2;155;79;150m'
BLUE='\033[48;2;0;56;168m'

# No Color
NC='\033[0m'

# Print the flag
printf "\n"
printf "${PINK}                          ${NC}\n"
printf "${PINK}                          ${NC}\n"
printf "${PURP}                          ${NC}\n"
printf "${BLUE}                          ${NC}\n"
printf "${BLUE}                          ${NC}\n"
printf "\n"
