#! /bin/bash
# Background Colors

## Trans flag colors
BLUE='\033[48;2;92;206;250m'
PINK='\033[48;2;245;169;184m'
WHIT='\033[48;2;255;255;255m'

## Gay flag colors
DGREE='\033[48;2;7;141;112m'
LGREE='\033[48;2;152;232;193m'
WHITE='\033[48;2;255;255;255m'
LBLUE='\033[48;2;123;173;226m'
DBLUE='\033[48;2;61;26;120m'

# No Color
NC='\033[0m' # No Color

# Print the flag
printf "\n"
printf "${BLUE}                          ${NC}\t${DGREE}                          ${NC}\n"
printf "${PINK}                          ${NC}\t${LGREE}                          ${NC}\n"
printf "${WHIT}                          ${NC}\t${WHITE}                          ${NC}\n"
printf "${PINK}                          ${NC}\t${LBLUE}                          ${NC}\n"
printf "${BLUE}                          ${NC}\t${DBLUE}                          ${NC}\n"
printf "\n"
